version: "3.5"

services:
  api01:
    image: rinhabe-2024-q1:latest
    hostname: api01
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200MB'

  api02:
    image: rinhabe-2024-q1:latest
    hostname: api02
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200MB'

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50mb'

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rinhadb
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha321
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100mb'

networks:
  default:
    driver: bridge
    name: rinha